# Generated by Django 3.1.4 on 2020-12-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_author', models.CharField(max_length=20)),
                ('blog_posted_timestamp', models.DateTimeField(auto_now=True)),
                ('blog_post', models.TextField(max_length=10000)),
            ],
        ),
    ]
