# Generated by Django 3.1.4 on 2020-12-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_posted_timestamp',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(default='Lorem ipsum dolorum', max_length=500),
        ),
    ]
