# Generated by Django 3.1.4 on 2021-01-08 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210106_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_description',
        ),
    ]
